language: c

services:
  - docker

env:
  - TEST_SUITE=gnat-community-2019

git:
  submodules: false

script:
  - if [ "$TEST_SUITE" = "gnat-community-2019" ]; then docker run -v $PWD:/app -w /app jklmnn/gnat:gpl.2019.spark /bin/sh -c "make test"; fi