on:                    # Run the workflow for each of the following event:
  push:                # - A branch is pushed or updated.
  pull_request:        # - A pull-request is openned or updated.
  workflow_dispatch:   # - A manual run of the workflow is requested from the GitHub web interface.
  release:
    types: [created]   # - A release is created.

jobs:
  main:
    strategy:
      fail-fast: false # Don't stop all the workflows when one of them fails.
      matrix:
        # List of build configurations to test
        include:
          - arch: generic
            simd: none
          - arch: x86_64
            simd: SSE2
          - arch: x86_64
            simd: AVX2

    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Install and setup Alire package manager
      - uses: alire-project/setup-alire@v1
        with:
          version: 1.2.0

      # Build the project using the validation build profile to enforce static analysis and coding style.
      - run: alr build --validation -- -XLIBKECCAK_ARCH=${{ matrix.arch }} -XLIBKECCAK_SIMD=${{ matrix.simd }}

      # Build the benchmark program
      - run: cd tests/benchmark && alr build -- -XLIBKECCAK_ARCH=${{ matrix.arch }} -XLIBKECCAK_SIMD=${{ matrix.simd }}

      # Build and run the Known Answer Tests
      - run: |
          cd tests/kat
          alr build --validation -- \
            -XLIBKECCAK_ARCH=${{ matrix.arch }} \
            -XLIBKECCAK_SIMD=${{ matrix.simd }} \
            -XLIBKECCAK_CONTRACTS=enabled \
            -XLIBKECCAK_RUNTIME_CHECKS=enabled \
            -XKAT_CONTRACTS=enabled \
            -XKAT_RUNTIME_CHECKS=enabled
          ./run-all-tests.sh

      # Build and run the unit tests
      - run: |
          cd tests/unit_tests
          alr build --validation -- \
            -XLIBKECCAK_ARCH=${{ matrix.arch }} \
            -XLIBKECCAK_SIMD=${{ matrix.simd }} \
            -XLIBKECCAK_CONTRACTS=enabled \
            -XLIBKECCAK_RUNTIME_CHECKS=enabled \
            -XUNIT_TESTS_CONTRACTS=enabled \
            -XUNIT_TESTS_RUNTIME_CHECKS=enabled
          alr run -s
